### ISSUE TITLE
Review player commands

### ISSUE THREAD

**Issue by neverbot** [maldorne/hexagon#14]
Full review and translation of the `player` commands:

- [x] ~ausente~ away
- [x] ~enterrar~ bury
- [ ] ~calendar~ (move to game `cmd` in **v2.1 Daggerfall**, #27)
- [x] ~comandos~ commands
- [x] ~combates~ combats
- [x] ~estado~ condition
- [x] ~configuracion~ configuration
- [x] ~considerar~ consider
- [x] ~coste~ cost
- [ ] ~diplomacy~ (postponed for now) 
- [x] ~carga~ encumbrance
- [x] ~equipo~ equipment
- [x] glance
- [x] grope
- [ ] ~group~ (postponed for now)
- [x] ~informar~ inform
- [x] inventory
- [x] kill
- [x] look
- [x] map
- [x] ~dinero~ money
- [x] past
- [x] ~apuntador~ pov
- [x] prompt
- [ ] ~quests~ (postponed to **v2.2 Edoras**, #26)
- [ ] ~ranking~ (postponed for now)
- [x] ~retirar~ retire
- [x] score
- [ ] ~buscar~ search (moved to `skill` in **v2.1 Daggerfall**, #25)
- [x] sheet
- [x] ~detener~ stop
- [x] time
- [x] ~cabalgar~ travel
- [x] ~modo~ verbose
- [x] whoami
- [x] ~cobardia~ wimpy
